### ISSUE TITLE
FR: Dark theme

### ISSUE THREAD

**Issue by gerroon** [KevinThomas0/noisedash#7]
Hi

Dark theme would be very helpful.

thanks

**Comment by KevinThomas0** [comment]
Hello,

Dark mode can be toggled in the sidebar which can be accessed by clicking the hamburger menu icon on the top left.

Let me know if that works all good for you.

**Comment by gerroon** [comment]
That sounds good,  my FR was based on the screenshots.

**Comment by KevinThomas0** [comment]
Nice, I do think I should move it from the sidebar to the account page though.
